"""add documents table

Revision ID: 1bfb44fd009c
Revises: de5740ce6aa2
Create Date: 2023-05-23 11:50:24.122076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfb44fd009c'
down_revision = 'de5740ce6aa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
