"""add accounts, documents, fund

Revision ID: 1c686b191949
Revises: 1bfb44fd009c
Create Date: 2023-05-25 12:38:12.023450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c686b191949'
down_revision = '1bfb44fd009c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=True),
    sa.Column('early_withdrawal_penalty', sa.Float(), nullable=True),
    sa.Column('fund_share_class_code', sa.String(), nullable=True),
    sa.Column('guaranteed_interest_rate', sa.Float(), nullable=True),
    sa.Column('maximum_contribution', sa.Float(), nullable=True),
    sa.Column('maximum_withdrawal', sa.Float(), nullable=True),
    sa.Column('minimum_contribution', sa.Float(), nullable=True),
    sa.Column('minimum_withdrawal', sa.Float(), nullable=True),
    sa.Column('withdrawal_limit', sa.Float(), nullable=True),
    sa.Column('withdrawal_limit_duration', sa.Integer(), nullable=True),
    sa.Column('withdrawal_limit_duration_type', sa.String(), nullable=True),
    sa.Column('withdrawal_settlement_period', sa.Integer(), nullable=True),
    sa.Column('withdrawal_settlement_period_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_fund_name'), 'funds', ['fund_name'], unique=False)
    op.create_index(op.f('ix_funds_id'), 'funds', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('contributions', sa.Float(), nullable=True),
    sa.Column('cumulative_income', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('withdrawals', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('investor_fund_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_fund_name'), 'accounts', ['fund_name'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('addresses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('addresses', 'updated_at')
    op.drop_column('addresses', 'created_at')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_fund_name'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_funds_id'), table_name='funds')
    op.drop_index(op.f('ix_funds_fund_name'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
