"""add addresses table 

Revision ID: de5740ce6aa2
Revises: 1962207d18ac
Create Date: 2023-05-23 11:37:23.894059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5740ce6aa2'
down_revision = '1962207d18ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('physical_address', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('postal_address', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('code', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('identity', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('identity_type', sa.String(), nullable=True))
    op.add_column('investors', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('investors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('investors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('investors', sa.Column('tax_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investors', 'tax_number')
    op.drop_column('investors', 'updated_at')
    op.drop_column('investors', 'created_at')
    op.drop_column('investors', 'date_of_birth')
    op.drop_column('investors', 'identity_type')
    op.drop_column('investors', 'identity')
    op.drop_column('investors', 'code')
    op.drop_column('addresses', 'postal_address')
    op.drop_column('addresses', 'physical_address')
    # ### end Alembic commands ###
